appname: example
package: com.example
version: 1
actions:
  testAction:
    parameters:
      - string
    outputs:
      - testModel
transforms:
  copy:
    triggers:
      - testModel
    output: testView
views:
  - testView
models:
  - name: testModel
    type: bag
  - name: testView
    type: bag
